name: twd_quiz
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'
dependencies:
  auto_route: ^5.0.4
  auto_route_generator: ^5.0.3
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.7.0
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  json_annotation: ^4.8.0
  equatable: ^2.0.5
  get_it: ^7.2.0
  flutter_svg: ^2.0.0+1
  graphic: ^2.0.3
  change_app_package_name: ^1.1.0
  circular_chart_flutter: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/